---
variants:
  - windows

overwrites:
  '["ServiceTemplate"]["tpl-service-service"]["enable_notifications"]': true
  '["ServiceTemplate"]["tpl-service-service"]["vars"]["service_windows_status"]': ['running']
