---
variants:
  - windows

overwrites:
  '["ServiceTemplate"]["tpl-service-service-windows"]["vars"]["service_windows_status"]': ['running']
  '["ServiceTemplate"]["tpl-service-service-windows"]["vars"]["vars"]["criticality"]': 'A'
