name: Feature request
description: Suggest an idea for this project
title: "[Feature request: A short sentence describing the feature]"
labels: ["enhancement"]
assignees: [""]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to make the Monitoring Plugins better.
        Please complete the below form to ensure we have all the details to get things started.
  - type: textarea
    id: input
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        Please describe the desired behavior, pitch your idea, or suggest improvements
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        Have you considered alternative solutions or implementations? Do you have an idea on how this should be implemented? Let us know! A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: info
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.